language: julia
julia:
    - 0.6
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.build("CutShortURL"); Pkg.test("CutShortURL"; coverage=true)';
after_success:
    - julia -e 'cd(Pkg.dir("CutShortURL")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
